TOP_CATEGORIES: dict[str, list[str]] = {
    "Text": ["Text (base)"],
    "Data": ["Data (base)"],
    "Code": [
        "Code: Web (JS/TS/React)",
        "Code: Python",
        "Code: C/C++",
        "Code: C#/.NET",
        "Code: Rust",
        "Code: Java/Gradle",
        "Code: Kotlin/Android",
        "Code: Swift/Xcode",
        "Code: Go",
        "Code: Shell/DevOps",
    ],
}

EXTENSION_SETS: dict[str, list[str]] = {
    "Text (base)": [".txt", ".md", ".rst", ".tex", ".rtf"],
    "Data (base)": [".json", ".yaml", ".yml", ".xml", ".csv", ".tsv", ".log", ".ini"],
    "Code: Web (JS/TS/React)": [
        ".js",
        ".mjs",
        ".cjs",
        ".ts",
        ".tsx",
        ".jsx",
        ".css",
        ".scss",
        ".sass",
        ".less",
        ".html",
        ".htm",
        ".json",
    ],
    "Code: Python": [".py", ".pyi", ".pyx", ".pxd", ".pxi"],
    "Code: C/C++": [".c", ".h", ".cpp", ".hpp", ".cc", ".hh", ".inl", ".tpp", ".cmake", ".hxx", ".cxx"],
    "Code: C#/.NET": [".cs", ".csproj", ".sln", ".props", ".targets", ".config"],
    "Code: Rust": [".rs", ".toml"],
    "Code: Java/Gradle": [".java", ".gradle", ".groovy", ".properties", ".xml"],
    "Code: Kotlin/Android": [".kt", ".kts", ".xml"],
    "Code: Swift/Xcode": [".swift", ".xcconfig"],
    "Code: Go": [".go", ".mod", ".sum"],
    "Code: Shell/DevOps": [
        ".sh",
        ".bash",
        ".zsh",
        ".ps1",
        ".psm1",
        ".cmd",
        ".bat",
        ".dockerfile",
        ".tf",
        ".tfvars",
        ".env",
        ".conf",
    ],
}
